AWSTemplateFormatVersion: 2010-09-09
Description: Create a basic CodeCommit repository

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: "Standard Details"
      Parameters:
        - AppName
        - Environment
    - Label:
        default: "Repo Details"
      Parameters:
        - RepoDescription

Parameters:
  AppName:
    Type: String
    Default: infra
    Description: Name of the application (lowercase). Use infra for platform.
  Environment:
    Type: String
    Default: shared-services
    Description: An environment name that is prefixed to resource names
    AllowedValues:
    - dev
    - test
    - prod
    - shared-services
  RepoDescription:
    Type: String
    Description: Enter a brief description of the repos purpose.

Resources:
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Ref RepoDescription
      RepositoryName: !Sub ${AppName}-${Environment}-Repo

Outputs:
 RepositoryName:
  Description: Name of the repository.
  Value: !GetAtt CodeCommitRepo.Name
  Export:
    Name: !Join ['-', [!Ref AppName, !Ref Environment, 'RepoName']]
