AWSTemplateFormatVersion: 2010-09-09
Description:  Basic EC2 template

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: "Standard Details"
      Parameters:
        - AppName
        - Environment
    - Label:
        default: "EC2 Details"
      Parameters:
        - InstanceType
        - VolumeSize
        - AMIId
        - KeyName
        - ServerSubnet        
        - EC2SecurityGroupIds

Parameters:
  AppName:
    Type: String
    Default: infra
    Description: Name of the local application. Same as Pipeline Global.
  Environment:
    Type: String
    Default: shared-services
    Description: This is the name of the LOCAL environment.
    AllowedValues:
    - dev
    - test
    - prod
    - shared-services
  VolumeSize:
    Type: Number
    Default: 60
    MinValue: 20
    Description: Enter the size of the Root volume in GB.  
  AMIId:
    Type: AWS::EC2::Image::Id
    Description: Please enter the amiid for the ec2 instaces to use
    Default: ami-0921802cb0717d0da
  InstanceType:
    Type: String
    Default: r6i.xlarge
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: please enter existing EC2 Key Pair for the instaces to use for SSH/RDP login
  EC2SecurityGroupIds:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Please select a security group to use for the EC2 hosts.
  ServerSubnet:
    Description: 'server subnet ID'
    Type: String  

Resources:
# EC2 defination
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroupIds:
        - !Ref 'EC2SecurityGroupIds'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'AMIId'
      IamInstanceProfile: !Ref ServerInstanceProfile
      SubnetId: !Ref ServerSubnet 
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref AppName, !Ref Environment, 'Server']]
        - Key: 'Environment'
          Value: !Ref Environment
        - Key: Application
          Value: !Ref AppName
      BlockDeviceMappings:    #Root Volume Defination
        - DeviceName: '/dev/xvda'
          Ebs:
            DeleteOnTermination: true 
            VolumeSize: !Ref VolumeSize
            VolumeType: gp3     

  ServerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"
      RoleName: !Sub "${Environment}-EC2Role"
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ServerInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - !Ref ServerRole

Outputs:
  ServerIP:
    Description: Server Private IP
    Value: !GetAtt EC2Instance.PrivateIp