AWSTemplateFormatVersion: '2010-09-09'
Description: Create SSM Endpoints and Security Group in ap-southeast-2.
#Filename: Purple-SSMEnd.yaml
#Version: 1.0
#Description: This creates Endpoints for SSM, SSMMessages & EC2Messages.
# Mutiple VPCs can use these endpoints if they have VPC Peering and routes.
# If configuring for multiple VPCs, ensure the CIDR range covers all VPCs
Parameters:
  AppName:
    Type: String
    Default: infra
    Description: Name of the local application. Same as Pipeline Global.
  Environment:
    Type: String
    Default: shared-services
    Description: This is the name of the LOCAL environment.
    AllowedValues:
    - dev
    - preprod
    - prod
    - test
    - shared-services
    - shared-network
  CIDRIP:
    Type: String
    Description: Enter the CIDR range for the SG.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/08-28
    Default: 10.10.0.0/16
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Enter the VPC ID to assign the Security Groups to.
    Default: vpc-05775352b361b9767

#  SUB01:
#    Type: AWS::EC2::Subnet::Id
#    Description: Enter the first subnet Id.
#  SUB02:
#    Type: AWS::EC2::Subnet::Id
#    Description: Enter the second subnet Id.
#  SUB03:
#    Type: AWS::EC2::Subnet::Id
#    Description: Enter the third subnet Id.
Resources:
  SSMSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCID
      GroupDescription: "Security Group for SSM"
      GroupName:
        'Fn::Join': [ "-", [!Ref AppName, !Ref Environment, "Endpoint", "SG"]]
      Tags:
        -
          Key: Name
          Value:
            'Fn::Join': [ "-", [!Ref AppName, !Ref Environment, "Endpoint", "SG"]]
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: !Ref CIDRIP
#  SSMEnd:
#    Type: AWS::EC2::VPCEndpoint
#    Properties:
#      VpcId: !Ref VPCID
#      ServiceName: com.amazonaws.ap-southeast-2.ssm
#      SubnetIds:
#      - !Ref SUB01
#      - !Ref SUB02
#      - !Ref SUB03
#      SecurityGroupIds:
#      - !GetAtt SSMSG.GroupId
#      PrivateDnsEnabled: true
#      VpcEndpointType: Interface
#  SSMMEnd:
#    Type: AWS::EC2::VPCEndpoint
#    Properties:
#      VpcId: !Ref VPCID
#      ServiceName: com.amazonaws.ap-southeast-2.ssmmessages
#      SubnetIds:
#      - !Ref SUB01
#      - !Ref SUB02
#      - !Ref SUB03
#      SecurityGroupIds:
#      - !GetAtt SSMSG.GroupId
#      PrivateDnsEnabled: true
#      VpcEndpointType: Interface
#  EC2MEnd:
#    Type: AWS::EC2::VPCEndpoint
#    Properties:
#      VpcId: !Ref VPCID
#      ServiceName: com.amazonaws.ap-southeast-2.ec2messages
#      SubnetIds:
#      - !Ref SUB01
#      - !Ref SUB02
#      - !Ref SUB03
#      SecurityGroupIds:
#      - !GetAtt SSMSG.GroupId
#      PrivateDnsEnabled: true
#      VpcEndpointType: Interface
Outputs:
  SGOut:
    Description: The ID of the SecurityGroup
    Value: !Ref SSMSG
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", SGID ] ]
